// <auto-generated />
using System;
using LaWashSmartParking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaWashSmartParking.Infrastructure.Migrations
{
    [DbContext(typeof(SmartParkingDbContext))]
    partial class SmartParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("LaWashSmartParking.Domain.Entities.IoTDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ioTDevices");
                });

            modelBuilder.Entity("LaWashSmartParking.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeviceId")
                        .IsUnique()
                        .HasFilter("[AssignedDeviceId] IS NOT NULL");

                    b.HasIndex("Location")
                        .IsUnique();

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("LaWashSmartParking.Domain.Entities.ParkingUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IoTDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccupiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParkingSpotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkingUsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
